export const FETCH_RANDOM_USER_PROGRESS = "FETCH_RANDOM_USER_PROGRESS"
export const FETCH_RANDOM_USER_SUCCESS = "FETCH_RANDOM_USER";
export const FETCH_RANDOM_USER_ERROR = "FETCH_RANDOM_USER_ERROR";

